version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 7
    target-branch: "main"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - update-types: ["version-update:semver-major"]
      - dependency-name: "epub"
      - dependency-name: "openai"
      - dependency-name: "pdf-parse"
      - dependency-name: "@langchain/openai"
      - dependency-name: "@langchain/core"
      - dependency-name: "libsql"
      - dependency-name: "pkce-challenge"
      - dependency-name: "app-builder-lib"
    groups:
      # CherryStudio 自定义包
      cherrystudio-packages:
        patterns:
          - "@cherrystudio/*"

      # 核心框架
      core-framework:
        patterns:
          - "react"
          - "react-dom"
          - "electron"

      # 开发工具
      build-and-dev:
        patterns:
          - "@eslint*"
          - "@playwright/*"
          - "@swc/*"
          - "@testing-library/*"
          - "@vitejs/*"
          - "@vitest/*"
          - "dotenv-cli"
          - "electron-builder"
          - "electron-devtools-installer"
          - "electron-vite"
          - "eslint*"
          - "husky"
          - "lint-staged"
          - "npx-scope-finder"
          - "playwright"
          - "prettier"
          - "rollup-plugin-visualizer"
          - "typescript"
          - "vite"
          - "vitest"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
